apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-be-config
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://billing-db-service:5432/billing"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
