apiVersion: v1
kind: Service
metadata:
  name: billing-be-service
  labels:
    app: billing-be
spec:
  type: ClusterIP
  selector:
    app: billing-be
  ports:
    - name: http
      port: 8080
      targetPort: 8080
