apiVersion: v1
kind: Service
metadata:
  name: billing-fe-service
  labels:
    app: billing-fe
spec:
  type: ClusterIP
  selector:
    app: billing-fe
  ports:
    - name: http
      port: 80
      targetPort: 80
