apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: billing

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/zoonny/billing/web
    newTag: 71a41b4d899d7bd5888914d512d2555ce103a33f
  - name: ghcr.io/zoonny/billing/app
    newTag: 71a41b4d899d7bd5888914d512d2555ce103a33f
