apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: billing

resources:
- namespace.yaml
- ../../base

images:
- name: ghcr.io/zoonny/billing-be
  newTag: latest
- name: ghcr.io/zoonny/billing-fe
  newTag: latest
