apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: billing

resources:
  - namespace.yaml
  - ../../base

images:
  - name: ghcr.io/zoonny/billing/web
    newTag: 66f13abac96be7beaab64dcd51d8f9687f6691d6
  - name: ghcr.io/zoonny/billing/app
    newTag: 66f13abac96be7beaab64dcd51d8f9687f6691d6
