apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: billing-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zoonny/deploy-repo.git
    targetRevision: main
    path: billing-deploy/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: billing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
